### PR TITLE
Implement remote_ip on connections

### PR DESCRIPTION
**Pull request by baudehlo**
For haraka/Haraka#1423

### CODE REVIEW

**Comment by msimerson** [comment]
This unrelated to haraka/Haraka#1423 but that doesn't make it a bad idea. If we're going to set remote_ip, I'd almost rather we set it to ::1 instead of 127.0.0.1.

**Comment by msimerson** [comment]
Oh, and test it with Haraka to make sure it doesn't break any existing tests. (it shouldn't, but that's not the same as, "it doesn't")

**Comment by baudehlo** [comment]
Just tested current Haraka master with this change, passes 100% except for
redis tests (those really shouldn't run since I don't have redis), and:

✖ implicit_mx - mxs4am-a.josef-froehle.de

**Comment by baudehlo** [comment]
God I hate DNS tests:

```
$ host mxs4am-a.josef-froehle.de
mxs4am-a.josef-froehle.de has address 185.82.23.132
Host mxs4am-a.josef-froehle.de not found: 2(SERVFAIL)
```

**Pull request merged**
