### PR TITLE
Add missing server property and allow setImmediate in pluigns

### PR DESCRIPTION
**Pull request by smfreegard**

### CODE REVIEW

**Comment by msimerson** [comment]
LGTM. Just update Changes.md, merge & publish.

**Comment by smfreegard** [comment]
Ta - doesn't look like I've got permissions to npm publish though.   Username is 'smfreegard'.

**Comment by msimerson** [comment]
When I try to add you to the module as a collaborator, npm says, `user not found: smfreegard`

**Comment by smfreegard** [comment]
Do you need to add me to the Haraka organization first?  - the user definitely exists:

`````
smf@i7desktop:~/git/haraka-test-fixtures$ npm login
Username: smfreegard
Password: 
Email: (this IS public) steve@freegard.name
Logged in as smfreegard on https://registry.npmjs.org/.
`````

**Comment by msimerson** [comment]
Weird. I've just been able to add you to the Haraka collabs on npm (which I wasn't able to do before), but when I try to do the same on haraka-plugin-fixtures (where the same 3 collabs (haraka, myself, and baudehlo exist) I get that user not found error.

**Comment by smfreegard** [comment]
Ok - can you npm publish this and it should cure the test failures on the other PRs I've done.   I've no idea what the problem with npm is.

**Comment by msimerson** [comment]
````
$ npm publish
+ haraka-test-fixtures@1.0.18
````

I still don't know what's up with npm. I've been able to add your profile to a couple other @haraka modules that I couldn't before. I'll try again in the future and maybe whatever this issue is will have cleared.

**Pull request merged**
